# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [--strict]
  - repo: https://github.com/schuellerf/pre-commit-pyspelling
    rev: 0.1.0
    hooks:
      - id: pyspelling
        args: ["--config", ".spellcheck.yml"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.19.1'
    hooks:
      - id: mypy
        additional_dependencies:
          - PyYAML
          - types-PyYAML
          - types-requests
          - fastmcp>=3.0
          - requests
          - PyJWT
          - deepeval
          - llama-index
          - llama-index-core
          - llama-index-tools-mcp
          - llama-index-llms-openai
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2
    hooks:
      - id: autopep8
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pycqa/pylint
    rev: v4.0.5
    hooks:
      - id: pylint
        # always pass all classes, otherwise e.g. tests fail
        stages: [manual]
        pass_filenames: false
        args: [--recursive=y, src, tests]
        additional_dependencies:
          - PyYAML
          - types-PyYAML
          - types-requests
          - pytest
          - fastmcp>=3.0
          - requests
          - PyJWT
          - deepeval
          - llama-index
          - llama-index-core
          - llama-index-tools-mcp
          - llama-index-llms-openai
